spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/userdb
    username: postgres
    password: Postgr_SQL@12
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  jackson:
    deserialization:
      fail-on-unknown-properties: true
